[sendgrid]
api_key = "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"
from_email = "jt@allied-doors.com,nina@allied-doors.com,mikejr@allied-doors.com"
to_emails = "jt@allied-doors.com"
